services:
  influxdb3:
    container_name: influxdb3
    image: influxdb:3.9.3-core
    ports:
      - 8181:8181
    env_file:
      - requirements/influxDB/.env
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - type: bind
        source: ~/.influxdb3/data
        target: /var/lib/influxdb3
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://localhost:8181/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  collector:
    container_name: collector
    build: ./requirements/collector
    env_file:
      - requirements/influxDB/.env
    depends_on:
      influxdb3:
        condition: service_healthy

  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - requirements/grafana/.env
      - requirements/influxDB/.env
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSW}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      influxdb3:
        condition: service_healthy
    restart: unless-stopped

volumes:
  grafana_data:
    name: grafana_data
