apiVersion: 1

datasources:
  - name: InfluxDB-v3-SQL
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb3:8181
    jsonData:
      version: SQL
      dbName: ${INFLUXDB_BUCKET}
      httpMode: POST
      insecureGrpc: true
    isDefault: true
    editable: true
