apiVersion: 1

datasources:
  - name: InfluxDB-v3-SQL
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      version: SQL
      httpMode: POST
    secureJsonData:
      token: $TOKEN
    database: $DB
    isDefault: true
    editable: true
