apiVersion: 1

datasources:
  - name: InfluxDB-v3-SQL
    type: influxdb
    access: proxy
    url: http://influxdb3:8181
    jsonData:
      version: SQL
      httpMode: POST
    database: ${INFLUXDB_BUCKET}
    isDefault: true
    editable: true
